apps/dashboard/urls.py
from django.urls import path
from apps.dashboard import views


urlpatterns = [
    path('', views.PanelView.as_view(), name='panel'),
    path('login', views.AuthView.as_view(), name='login'),
    path('signup', views.SignupView.as_view(), name='signup'),
    path('logout', views.LogoutView.as_view(), name='logout'),
    path('credit', views.CreditView.as_view(), name='credit'),
    path('new-analyze', views.AnalyseFormView.as_view(), name='new-analyze'),
    path('follow-analyze', views.AnalyseView.as_view(), name='follow-analyze'),
    path('create-payment', views.CreatePaymentView.as_view(), name='create-payment'),
    path('iugu-notification', views.IuguNotificationView.as_view(), name='iugu-notification'),
    path('wait', views.WaitView.as_view(), name='wait'),
]

apps/site/urls.py
from django.urls import path, include
from apps.site import views


urlpatterns = [
    path('', views.HomeView.as_view(), name='home'),
    path('how-it-works', views.HowItWorksView.as_view(), name='how-it-works'),
    path('step-1', views.Step1View.as_view(), name='step-1'),
    path('step-2', views.Step2View.as_view(), name='step-2'),
    path('step-3', views.Step3View.as_view(), name='step-3'),
    path('plans', views.PlansView.as_view(), name='plans'),
    path('example', views.ExampleView.as_view(), name='example'),
]

expertise/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('apps.site.urls', 'site'), namespace='site')),
    path('dashboard/', include(('apps.dashboard.urls', 'dashboard'), namespace='dashboard')),
]

apps/site/views.py
from django.views.generic import TemplateView
from apps.core.models import Indicator, Report, Analyze


class HomeView(TemplateView):
    template_name = 'site/home.html'


class HowItWorksView(TemplateView):
    template_name = 'site/how-it-works.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data()
        context['indicators'] = Indicator.objects.all()
        return context


class Step1View(TemplateView):
    template_name = 'site/step-1.html'


class Step2View(TemplateView):
    template_name = 'site/step-2.html'


class Step3View(TemplateView):
    template_name = 'site/step-3.html'


class PlansView(TemplateView):
    template_name = 'site/plans.html'


class ExampleView(TemplateView):
    template_name = 'site/example.html'

    def get_context_data(self, **kwargs):
        analyze = Analyze.objects.filter(state=Analyze.STATES.analyzed).order_by('created').first()
        context = super().get_context_data()
        context['reports'] = Report.objects.filter(analyse=analyze)
        return context

apps/site/templates/site/example.html
{% extends "site/base.html" %}
{% load static %}


{% block content %}

	<h1 class="ff-fjalla text-uppercase fs-64 mt-5">
		Exemplo
	</h1>

	<p class="ff-poppins fs-20 mt-3">
		Você informa o dados do imóvel, e o sistema do Imóvel Periciado faz o resto. <strong>Faça sua transação imobiliária com segurança no que diz respeito a documentação!</strong>
	</p>

	<ul class="checklist-real-estate mt-3">
        {% for report in reports %}
            <li class="{% if report.state == 'ok' %}ok{% else %}not-ok{% endif %}" data-toggle="popover" data-container="body" data-placement="top" data-content="{{ report.indicator.description }}">
                {% if report.state == 'ok' %}
                    <i class="fa fa-check-circle float-right fs-30"></i>
                {% else %}
                    <i class="fas fa-times-circle float-right fs-30"></i>
                {% endif %}

                <small>{{ report.indicator.name }}</small><br>

                {% if report.observation %}
                    {{ report.observation }}
                {% elif report.indicator.observation_ok and report.state == 'ok' %}
                    {{ report.indicator.observation_ok }}
                {% elif report.indicator.observation_not_ok and report.state == 'not_ok' %}
                    {{ report.indicator.observation_not_ok }}
                {% endif %}

                <a href="#" class="indicator-details-link" data-toggle="tooltip" data-placement="top" title="Mais informações"><span style="display: block; height: 100%;"><i class="fas fa-question-circle"></i> <br>.<br>.</span></a>
            </li>
        {% endfor %}
    </ul>

    <a href="{% url "dashboard:signup" %}" class="btn btn-primary mt-5 text-uppercase fs-16 ff-poppins font-weight-bold">Solicitar Análise <i class="fas fa-arrow-right"></i></a>

{% endblock %}

{% block js %}
    <script>
    $(function () {
      $('[data-toggle="popover"]').popover();
      $('[data-toggle="tooltip"]').tooltip();

      $(document).on('focus', ':not(.popover)', function(){
        $('.popover').popover('hide');
        $('.tooltip').tooltip('hide');
    });

      $('[data-toggle=popover]').on('click', function (e) {
           $('[data-toggle=popover]').not(this).popover('hide');
        });

      $('.indicator-details-link').on('click', function (e) {
          e.preventDefault();
          $(this).closest('li').popover('show');
      });

    });
    </script>
{% endblock %}

apps/site/templates/site/home.html
{% extends "site/base.html" %}


{% block content %}
    <h1 class="ff-fjalla text-uppercase fs-64 mt-10">
        Verifique a documentação <br>
        do imóvel desejado.
    </h1>

    <p class="ff-poppins fs-20">
        Analisamos o histórico do imóvel desejado, e informamos de um jeito simples pra você.
    </p>

    <a href="{% url "site:how-it-works" %}" class="btn btn-primary mt-3 text-uppercase fs-16 ff-poppins font-weight-bold">Vamos Começar <i class="fas fa-arrow-right"></i></a>
{% endblock %}

apps/site/templates/site/how-it-works.html
{% extends "site/base.html" %}


{% block content %}

	<h1 class="ff-fjalla text-uppercase fs-64 mt-5">
		Como Funciona?
	</h1>

	<p class="ff-poppins fs-20 mt-3">
		A consulta de dados reúne algumas das informações mais valiosas que são necessárias na compra do imóvel.
	</p>
	<p class="ff-poppins fs-20 mt-3">
		Um Sistema que utiliza da mais alta e nova tecnologia para solicitação leitura e interpretação de documentos junto aos órgãos competentes, supervisionado por uma ampla equipe de advogados atuantes há mais de vinte anos na área de direito imobiliário.
	</p>

	<div class="row mt-5">
		{% for indicator in indicators %}
            <div class="col-md-4">
                <a data-toggle="modal" data-target="#itemmodal" class="item-tag text-primary">
                    {{ indicator.name }}
                </a>
            </div>
        {% endfor %}
	</div>

    <a href="{% url "site:example" %}" class="btn btn-primary mt-5 text-uppercase fs-16 ff-poppins font-weight-bold">Ver Exemplo <i class="fas fa-arrow-right"></i></a>

{% endblock %}

apps/site/templates/site/step-1.html
{% extends "site/base.html" %}


{% block content %}

		<h1 class="ff-fjalla text-uppercase fs-64 mt-5">
			VAMOS ENCONTRAR O<br>
			IMÓVEL
		</h1>

		<p class="ff-poppins fs-20 mt-3">
			Para conseguir toda a documentaçao é muito simples. Busque pelo Estado, CEP, Matrícula, Endereço, Nome do Proprietário ou o Tipo do Imóvel desejado (Apartamento, casa, etc).
		</p>

		<div class="row mt-5">
			<div class="col-md-12">
				<div class="form-group">
					<label class="text-uppercase fs-12">Endereço (Obrigatório)</label>
					<input type="text" class="form-control" placeholder="Ex: Rua Marechal Floriano Peixoto">
				</div>
			</div>
			<div class="col-md-6">
				<div class="form-group">
					<label class="text-uppercase fs-12">Matrícula (Número)</label>
					<input type="text" class="form-control" placeholder="Ex: 00000">
				</div>
			</div>
			<div class="col-md-6">
				<div class="form-group">
					<label class="text-uppercase fs-12">Tipo do imóvel</label>
					<select name="" class="form-control">
						<option value="">-- Selecione o tipo --</option>
						<option value="">Apartamento</option>
						<option value="">Casa</option>
						<option value="">Terreno</option>
					</select>
				</div>
			</div>
			<div class="col-md-6">
				<div class="form-group">
					<label class="text-uppercase fs-12">Nome do proprietário (opcional)</label>
					<input type="text" class="form-control" placeholder="Ex: João Paulo da Silva">
				</div>
			</div>
			<div class="col-md-6">
				<div class="form-group">
					<label class="text-uppercase fs-12">Complemento (opcional)</label>
					<input type="text" class="form-control" placeholder="Ex: Bloco b, ap 200">
				</div>
			</div>
		</div>

		<a href="{% url "site:step-2" %}" class="btn btn-primary mt-5 text-uppercase fs-16 ff-poppins font-weight-bold">Solicitar Análise <i class="fas fa-arrow-right"></i></a>

{% endblock %}

apps/site/templates/site/step-2.html
{% extends "site/base.html" %}


{% block content %}

	<h1 class="ff-fjalla text-uppercase fs-64 mt-5">
		Meus Pedidos <a href="{% url "site:how-it-works" %}" class="btn btn-secondary float-right">Como Funciona <i class="fas fa-question-circle"></i></a>
	</h1>

	<p class="ff-poppins fs-20 mt-3">
		Para maiores análises, abra um ticket. Nós enviaremos um orçamento em menos de 48 horas.
	</p>

	<div class="text-primary shadow rounded p-5">
	  <div class="font-weight-bold fs-20"><i class="far fa-check-circle"></i> Hipoteca</div>
	  <div class="font-weight-bold mt-4 fs-20"><i class="far fa-check-circle"></i> Penhora</div>
	  <div class="font-weight-bold mt-4 fs-20"><i class="far fa-check-circle"></i> Indisponibilidade de bens</div>
	  <div class="font-weight-bold mt-4 fs-20"><i class="far fa-check-circle"></i> Certidão Trabalhista</div>
	  <div class="font-weight-bold mt-4 fs-20"><i class="far fa-check-circle"></i> IPTU (não disponível para todas as localidades)</div>
	  <div class="font-weight-bold mt-4 fs-20"><i class="far fa-check-circle"></i> Alienação Fidunciária</div>
	  <div class="font-weight-bold mt-4 fs-20"><i class="far fa-check-circle"></i> Confirmação do proprietário informado</div>
	  <div class="font-weight-bold mt-4 fs-20"><i class="far fa-check-circle"></i> Certidão Estadual</div>
	  <div class="font-weight-bold mt-4 fs-20"><i class="far fa-check-circle"></i> Certidão Federal</div>

	  <div class="border-left border-4 mt-5 border-primary">
			<h2 class="ml-3 fs-30 font-weight-bold">
				<span class="text-dark fs-12 text-uppercase">Valor Total</span><br>
				52,90
			</h2>
		</div>
	</div>

	<a href="{% url "site:step-3" %}" class="btn btn-primary mt-5 text-uppercase fs-16 ff-poppins font-weight-bold">Ir para checkout <i class="fas fa-arrow-right"></i></a>
{% endblock %}

apps/site/templates/site/step-3.html
{% extends "site/base.html" %}
{% load static %}


{% block content %}

	<h1 class="ff-fjalla text-uppercase fs-64 mt-5">
		Checkout
	</h1>

	<p class="ff-poppins fs-20 mt-3">
		Complete os campos com os dados do seu cartão.
	</p>

	<div class="text-primary shadow rounded p-5">
			<h5 class="fa-poppins font-weight-bold text-dark mb-5">Dados do cartão</h5>
		  <div class="row">
			<div class="col-md-12">
				<div class="form-group">
					<label class="text-uppercase fs-12">Nome do titular</label>
					<input type="text" class="form-control" placeholder="Ex: Luciano Camargo">
				</div>
			</div>
			<div class="col-md-6">
				<div class="form-group">
					<label class="text-uppercase fs-12">Número do cartão</label>
					<input type="text" class="form-control" placeholder="Ex: 0000 0000 0000 0000">
				</div>
			</div>
			
			<div class="col-md-3">
				<div class="form-group">
					<label class="text-uppercase fs-12">Validade</label>
					<input type="text" class="form-control" placeholder="Ex: 10/2030">
				</div>
			</div>
			<div class="col-md-3">
				<div class="form-group">
					<label class="text-uppercase fs-12">CVC <i class="fas fa-question-circle"></i></label>
					<input type="text" class="form-control" placeholder="Ex: 000">
				</div>
			</div>
			<div class="col-md-12 text-right">
				<div class="mt-3">
					<h3 class="text-uppercase text-dark fs-16 font-weight-bold ff-poppins">Seu pagamento sera processado pela:</h3>
					<img src="https://upload.wikimedia.org/wikipedia/commons/thumb/8/80/Logo_PagSeguro.png/800px-Logo_PagSeguro.png" width="200" class="mr-4">
					<img src="{% static "img/bandeiras.png" %}">
				</div>
			</div>
		</div>
	</div>

	<a href="#" class="btn btn-primary mt-5 text-uppercase fs-16 ff-poppins font-weight-bold">Finalizar Compra <i class="fas fa-arrow-right"></i></a>&nbsp;&nbsp;
	<a href="#" class="btn btn-light mt-5 text-uppercase fs-16 ff-poppins font-weight-bold">Ou Pagar com Boleto <i class="fas fa-barcode"></i></a>
{% endblock %}