apps/dashboard/urls.py
from django.urls import path
from apps.dashboard import views


urlpatterns = [
    path('', views.PanelView.as_view(), name='panel'),
    path('login', views.AuthView.as_view(), name='login'),
    path('signup', views.SignupView.as_view(), name='signup'),
    path('logout', views.LogoutView.as_view(), name='logout'),
    path('credit', views.CreditView.as_view(), name='credit'),
    path('new-analyze', views.AnalyseFormView.as_view(), name='new-analyze'),
    path('follow-analyze', views.AnalyseView.as_view(), name='follow-analyze'),
    path('create-payment', views.CreatePaymentView.as_view(), name='create-payment'),
    path('iugu-notification', views.IuguNotificationView.as_view(), name='iugu-notification'),
    path('wait', views.WaitView.as_view(), name='wait'),
]

expertise/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('apps.site.urls', 'site'), namespace='site')),
    path('dashboard/', include(('apps.dashboard.urls', 'dashboard'), namespace='dashboard')),
]

apps/dashboard/forms.py
from django import forms
from apps.core.models import Analyze


class AnalyseForm(forms.ModelForm):
    class Meta:
        model = Analyze
        fields = ['zipcode', 'address', 'number', 'registration_number', 'block', 'lot', 'type', 'complement']
        widgets = {
            'zipcode': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Código postal'}),
            'address': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Não coloque cidade e estado'}),
            'number': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Coloque 0 se não existir'}),
            'registration_number': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Apenas números'}),
            'block': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Apenas números'}),
            'lot': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Apenas números'}),
            'complement': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Insira informações complementares do imóvel'}),
            'type': forms.Select(attrs={'class': 'form-control'}),
        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['lot'].required = False
        self.fields['registration_number'].required = False
        self.fields['block'].required = False

    def clean(self):
        cleaned_data = super().clean()
        registration_number = cleaned_data.get('registration_number')
        block = cleaned_data.get('block')
        lot = cleaned_data.get('lot')

        if not registration_number and not block and not lot:
            self.add_error('registration_number', 'Preencha a matrícula, ou quadra e lote')

        if not registration_number and block and not lot:
            self.add_error('lot', 'Este campo é obrigatório')

apps/dashboard/views.py
import requests
from requests.auth import HTTPBasicAuth
from datetime import timedelta
from decimal import Decimal
from django.utils import timezone
from django.views.generic import TemplateView, View
from django.views.generic.edit import CreateView, FormView
from django.contrib.auth.views import LoginView, logout_then_login
from django.contrib.auth.decorators import login_required
from django.db.models import Q
from django.urls import reverse
from django.shortcuts import redirect
from django.contrib.auth import login
from django.contrib import messages
from django.conf import settings
from django.utils.decorators import method_decorator
from django.http import JsonResponse
from django.views.decorators.csrf import csrf_exempt
from templated_email import send_templated_mail
from django.db import transaction
from pagseguro import PagSeguro
from apps.core.models import Analyze, Report, Account, User, Charge
from apps.core.forms import UserForm
from apps.dashboard.forms import AnalyseForm


pg = PagSeguro(email="esabadini@yahoo.com", token="31E3149BE6E246428498561D5D261021")


@method_decorator(login_required, name='dispatch')
class PanelView(TemplateView):
    template_name = 'dashboard/panel.html'
    http_method_names = ['get', 'post']

    def get_context_data(self, **kwargs):
        data = super().get_context_data()
        extra_args = []

        if self.request.method == 'POST':
            s = self.request.POST.get('s')
            data['s'] = s.strip()
            extra_args = [
                Q(registration_number__contains=s) |
                Q(address__icontains=s) |
                Q(block__contains=s) |
                Q(zipcode__contains=s) |
                Q(lot__contains=s)
            ]

        data['analyzes'] = Analyze.objects.filter(user=self.request.user, *extra_args)
        return data

    def post(self, *args, **kwargs):
        return super().get(*args, **kwargs)


class AuthView(LoginView):
    template_name = 'dashboard/login.html'
    redirect_authenticated_user = True


class SignupView(FormView):
    template_name = 'dashboard/signup.html'
    form_class = UserForm

    def form_valid(self, form):
        user = form.save(commit=False)
        user.username = user.email
        user.set_password(form.cleaned_data['password'])
        user.save()
        login(self.request, user)

        if user.type == 'owner':
            return redirect(self.get_success_url())

        return redirect(reverse('dashboard:wait'))

    def get_success_url(self):
        messages.success(self.request, 'Bem vindo. Este é o seu painel, fique a vontade para explorar nossa ferramenta.')
        return reverse('dashboard:panel')


@method_decorator(login_required, name='dispatch')
class LogoutView(View):
    def get(self, request):
        return logout_then_login(request)


@method_decorator(login_required, name='dispatch')
class CreditView(TemplateView):
    template_name = 'dashboard/credit.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data()
        context['account'] = Account.objects.filter(user=self.request.user).first()
        context['charges'] = Charge.objects.filter(user=self.request.user).order_by('-created')
        return context


@method_decorator(login_required, name='dispatch')
class WaitView(TemplateView):
    template_name = 'dashboard/wait.html'


@method_decorator(login_required, name='dispatch')
class AnalyseFormView(CreateView):
    template_name = 'dashboard/analyze-form.html'
    model = Analyze
    form_class = AnalyseForm

    def get_context_data(self, **kwargs):
        context = super().get_context_data()
        context['account'] = Account.objects.filter(user=self.request.user).first()
        return context

    def get_success_url(self):
        return reverse('dashboard:panel')

    def form_valid(self, form):
        with transaction.atomic():
            form.instance.user = self.request.user
            messages.success(self.request, 'Solicitação de análise efetuada com sucesso!')
            response = super().form_valid(form)

            account = Account.objects.filter(user=self.request.user).first()
            account.credit -= account.request_price
            account.save()

        send_templated_mail(
            template_name='new-analyse',
            from_email=settings.DEFAULT_FROM_EMAIL,
            recipient_list=[self.request.user.email],
            context={'analyze': form.instance}
        )

        return response


@method_decorator(login_required, name='dispatch')
class AnalyseView(TemplateView):
    template_name = 'dashboard/analyze.html'

    def get_context_data(self, **kwargs):
        analyse = Analyze.objects.get(pk=self.request.GET['code'], user=self.request.user)

        data = super().get_context_data()
        data['analyze'] = analyse
        data['reports'] = Report.objects.filter(analyse=analyse)
        return data


@method_decorator(login_required, name='dispatch')
class CreatePaymentView(View):
    def post(self, request):
        amount_raw = round(Decimal(''.join(c for c in request.POST['amount'] if c.isdigit() or c == '.')), 2)
        amount = int(''.join(c for c in str(amount_raw) if c.isdigit()))

        url = "https://api.iugu.com/v1/invoices"

        data = {
            'email': request.user.email,
            'due_date': (timezone.now() + timedelta(days=2)).isoformat(),
            'ensure_workday_due_date': 'true',
            'items': [
                {
                    'quantity': 1,
                    'description': 'Crédito em conta',
                    'price_cents': amount
                }
            ],
            'payer': {
                'cpf_cnpj': request.user.document,
                'name': request.user.first_name,
                'address.zip_code': request.user.zipcode,
                'address.number': request.user.number,
                'address.street': request.user.address,
                'address.district': request.user.district,
            },
            'notification_url': 'https://imovelpericiado.com.br/dashboard/iugu-notification',
            'return_url': 'https://imovelpericiado.com.br/dashboard/new-analyze'
        }

        invoice = requests.post(url, json=data, auth=HTTPBasicAuth('a0e1ac8ce3f59b551d23976c5f996821', '')).json()

        charge = Charge()
        charge.amount = amount_raw
        charge.ref = invoice['id']
        charge.user = request.user
        charge.save()

        return JsonResponse({'url': invoice['secure_url']})


@method_decorator(csrf_exempt, name='dispatch')
class IuguNotificationView(View):
    def post(self, request):
        data = dict(request.POST)
        status = data['data[status]'][0]
        ref = data['data[id]'][0]
        charge = Charge.objects.get(ref=ref)

        if status == 'paid':
            with transaction.atomic():
                charge.state = Charge.STATES.paid
                charge.save()

                account = Account.objects.filter(user=charge.user).first()
                account.credit += charge.amount
                account.save()

        return JsonResponse({'status': 'Ok'})

apps/dashboard/templates/dashboard/analyze-form.html
{% extends "dashboard/base.html" %}
{% load static %}

{% block content %}
    <div class="row">
        <div class="col-md-6">
            <h1 class="ff-fjalla text-uppercase fs-64">
                {% if analyze %}
                    ACOMPANHANDO PERÍCIA
                {% else %}
                    NOVA PERÍCIA
                {% endif %}
            </h1>

            <p class="mb-4">Para que a perícia acontença, precisamos do máximo de informações referentes ao imóvel</p>
            <hr class="mb-4">

            <p class="mb-4 mt-0">
                <small class="text-danger">Campos com <strong>*</strong> (asterisco) são obrigatórios.</small><br>
                <small class="text-danger">Você pode preencher apenas a matrícula. Caso não saiba o seu número da matrícula, preencha a quadra e lote.</small><br>
                <small class="text-danger">Buscamos automáticamente a cidade e estado a partir de seu CEP, portanto não erre.</small><br>
            </p>

            {% if account.credit < account.request_price %}
                <div class="row">
                    <div class="col-md-12">
                        <div class="rounded-0 mt-3 alert alert-warning">
                            <p class="mt-3 float-left"><i class="fas fa-exclamation-triangle"></i> Sua conta não possui créditos suficiente para solicitar uma nova perícia.</p>
                            <a href="{% url "dashboard:credit" %}" class="btn btn-warning btn-sm shadow float-right"><i class="fas fa-coins"></i> Adicionar Créditos</a>
                        <div class="clearfix"></div></div>
                    </div>
                </div>
                <hr>
            {% endif %}

            <form method="post" novalidate>
                {% csrf_token %}
                <div class="row">
                    <div class="col-lg-3">
                        <div class="form-group">
                            <label>Tipo *</label>
                            {{ form.type }}
                            {% for error in form.type.errors %}
                              <small><strong class="text-danger">{{ error }}</strong></small>
                          {% endfor %}
                        </div>
                    </div>
                    <div class="col-lg-3">
                        <div class="form-group">
                            <label>CEP *</label>
                            {{ form.zipcode }}
                            {% for error in form.zipcode.errors %}
                              <small><strong class="text-danger">{{ error }}</strong></small>
                          {% endfor %}
                        </div>
                    </div>
                    <div class="col-lg-6">
                        <div class="form-group">
                            <label>Endereço *</label>
                            {{ form.address }}
                            {% for error in form.address.errors %}
                              <small><strong class="text-danger">{{ error }}</strong></small>
                            {% endfor %}
                        </div>
                    </div>
                    <div class="col-lg-3">
                        <div class="form-group">
                            <label>Número *</label>
                            {{ form.number }}
                            {% for error in form.number.errors %}
                                  <small><strong class="text-danger">{{ error }}</strong></small>
                              {% endfor %}
                        </div>
                    </div>
                    <div class="col-lg-9">
                        <div class="form-group">
                            <label>Complementos</label>
                            {{ form.complement }}
                            {% for error in form.complement.errors %}
                                  <small><strong class="text-danger">{{ error }}</strong></small>
                              {% endfor %}
                        </div>
                    </div>
                    <div class="col-lg-4">
                        <div class="form-group">
                            <label>Mátricula</label>
                            {{ form.registration_number }}
                              {% for error in form.registration_number.errors %}
                              <small><strong class="text-danger">{{ error }}</strong></small>
                          {% endfor %}
                        </div>
                    </div>
                    <div class="col-lg-4">
                        <div class="form-group">
                            <label>Quadra/Bloco se houver</label>
                            {{ form.block }}
                                {% for error in form.block.errors %}
                              <small><strong class="text-danger">{{ error }}</strong></small>
                          {% endfor %}
                        </div>
                    </div>
                    <div class="col-lg-4">
                        <div class="form-group">
                            <label>Lote/N do AP se houver</label>
                            {{ form.lot }}
                                {% for error in form.lot.errors %}
                              <small><strong class="text-danger">{{ error }}</strong></small>
                          {% endfor %}
                        </div>
                    </div>
                </div>

                <p class="mt-3 mb-0"><small>Verifique se os dados estão corretos antes de solicitar a perícia</small></p>

                {% if account.credit >= account.request_price %}
                    <button type="submit" class="btn float-right btn-primary btn-sm shadow">SOLICITAR PERÍCIA</button>
                {% endif %}
            </form>
        </div>

        <div class="col-md-6 text-right">
            <img src="{% static "img/banner.png" %}" class="img-fluid">
        </div>
    </div>
{% endblock %}

{% block js %}
    <script src="https://cdn.jsdelivr.net/npm/cep-promise/dist/cep-promise.min.js"></script>
    <script>
        var zipcode = document.getElementById("id_zipcode");

        zipcode.onblur = function() {
            var address = document.getElementById("id_address");

            cep(this.value).then(function (data) {
                address.value = data.street;
            });
        };
    </script>
{% endblock %}

apps/dashboard/templates/dashboard/analyze.html
{% extends "dashboard/base.html" %}
{% load static %}

{% block page_name %}
    {% if analyze %}
        PERÍCIA {{ analyze.code }}
    {% endif %}

{% endblock %}

{% block content %}
    <div class="row">
        <div class="col-md-6">
            {% if analyze.state == 'analyzed' %}
                <p class="mt-3">Seu imóvel, possui alguma irregularidade, quer soluciona-la? Clique no botão abaixo e solicite um orçamento.</p>
                <a href="#" class="btn btn-warning">Solicitar Orçamento</a>
            {% endif %}

            {% if analyze.state == 'analyzed' and request.user.can_download_registration %}
              <hr class="mt-3 mb-3">
              <a href="{{ analyze.registration.url }}" target="_blank" class="btn btn-primary"><i class="fas fa-download"></i> Baixar Matrícula</a>
            {% endif %}

            <div class="card mt-4 shadow-sm">
                <div class="card-body">
                   Solicitada em: <strong>{{ analyze.created }}</strong><br>
                    <hr>
                   CEP: <strong>{{ analyze.zipcode }}</strong><hr>
                   Endereço: <strong>{{ analyze.address }}</strong><hr>
                   Número: <strong>{{ analyze.number }}</strong><hr>
                   Matrícula: <strong>{{ analyze.registration_number|default:"N/D" }}</strong><hr>
                   Quadra: <strong>{{ analyze.block|default:"N/D" }}</strong><hr>
                   Lote: <strong>{{ analyze.lot|default:"N/D" }}</strong>
                </div>
            </div>

        </div>

        <div class="col-md-6">

            {% if analyze.state != 'analyzed' %}
                <div class="alert mt-3 alert-warning shadow-sm">
                    <strong>Perícia em andamento, aguarde... <i class="fas fa-clock"></i></strong><br>
                    <hr>
                    Sua perícia é feita normalmente em até 24 horas. Dependendo das datas festivas e dos cartórios, esse prazo pode aumentar para até 5 dias úteis.
                </div>
            {% else %}
                <ul class="checklist-real-estate mt-3">
                    {% for report in reports %}
                        <li class="{% if report.state == 'ok' %}ok{% else %}not-ok{% endif %}" data-toggle="popover" data-container="body" data-placement="top" data-content="{{ report.indicator.description }}">
                            {% if report.state == 'ok' %}
                                <i class="fa fa-check-circle float-right fs-30"></i>
                            {% else %}
                                <i class="fas fa-times-circle float-right fs-30"></i>
                            {% endif %}

                            <small>{{ report.indicator.name }}</small><br>

                            {% if report.observation %}
                                {{ report.observation }}
                            {% elif report.indicator.observation_ok and report.state == 'ok' %}
                                {{ report.indicator.observation_ok }}
                            {% elif report.indicator.observation_not_ok and report.state == 'not_ok' %}
                                {{ report.indicator.observation_not_ok }}
                            {% endif %}

                            <a href="#" class="indicator-details-link" data-toggle="tooltip" data-placement="top" title="Mais informações"><span style="display: block; height: 100%;"><i class="fas fa-question-circle"></i> <br>.<br>.</span></a>
                        </li>
                    {% endfor %}
                </ul>
            {% endif %}
        </div>
    </div>
{% endblock %}

{% block js %}
    <script>
    $(function () {
      $('[data-toggle="popover"]').popover();
      $('[data-toggle="tooltip"]').tooltip();

      $(document).on('focus', ':not(.popover)', function(){
        $('.popover').popover('hide');
        $('.tooltip').tooltip('hide');
      });

      $('[data-toggle=popover]').on('click', function (e) {
           $('[data-toggle=popover]').not(this).popover('hide');
        });

      $('.indicator-details-link').on('click', function (e) {
          e.preventDefault();
          $(this).closest('li').popover('show');
      });

    });
    </script>
{% endblock %}

apps/dashboard/templates/dashboard/credit.html
{% extends "dashboard/base.html" %}

{% block page_name %}CRÉDITOS{% endblock %}

{% block content %}
    <p>Aqui você acompanha o status financeiro da sua conta. Realize suas recargas e comece a usar.</p>

    <hr>

    <div class="row mt-4">
        <div class="col-md-6">
            <small>Seu saldo atual em Reais é de:</small>
            <h1><strong>{{ account.credit|floatformat:2 }}</strong></h1>

            <hr>

            <div class="row">
                <div class="col-md-4">
                    <input type="number" id="amount" class="form-control form-control-lg mb-4" value="52.90" step="1">
                </div>
                <div class="col-md-8">
                    <p class="mt-3"><small>Digite o valor em Reais que deseja adicionar de crédito a sua conta.</small></p>
                </div>
            </div>



            <div class="alert alert-danger fs-14 rounded-0">
                <p class="mb-1"><i class="fas fa-coins"></i> O valor minímo de crédito que pode ser adicionado a sua conta é de R$ 52,90.</p>
                <p class="mb-1"><i class="fas fa-credit-card"></i> Pagamentos feitos através de cartão de crédito, são processados no mesmo instante em sua conta.</p>
                <p class="mb-0"><i class="fas fa-barcode"></i> Pagamentos feitos através de boleto bancário, podem levar até 3 dias úteis.</p>
            </div>

            <p>Por motivos de segurança, usamos a Iugu como meio de pagamento, por favor, clique no botão para colocar créditos.</p>
            <hr class="border-0">

            <a href="#" class="btn btn-sm btn-warning" data-toggle="modal" data-target="#card-modal" id="pagar-com-iugu">
                <h1><i class="fas fa-credit-card"></i></h1>
                <small class="text-uppercase fs-20">Pagar</small>
            </a>
        </div>

        <div class="col-md-6">
            <hr class="mt-5 mb-5 d-lg-none">

            <h5 class="mb-3"><i class="fas fa-history"></i> HISTÓRICO</h5>

            <p><small>Suas faturas aparecem aqui, você pode acompanhar todo o histórico de valores creditados para organizar as finanças.</small></p>

            <table class="table shadow-sm table-bordered tablesaw" data-tablesaw-mode="stack">
                <thead>
                    <tr class="fs-12">
                        <th>DATA</th>
                        <th>VALOR</th>
                        <th>STATUS</th>
                    </tr>
                </thead>
                <tbody>
                    {% for charge in charges %}
                        <tr>
                            <td>{{ charge.created }}</td>
                            <td>{{ charge.amount }}</td>
                            <td>{{ charge.state }}</td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>


        </div>
    </div>
{% endblock %}

{% block js %}
    <script>
        jQuery(function ($) {
            $('#pagar-com-iugu').click(function (e) {
                e.preventDefault();

                var amount = $('#amount').val();
                var code = $('#code');
                var $this = this;

                Swal.showLoading();


                if (parseFloat(amount) < 52.90) {
                    Swal.fire(
                      'Opsss!',
                      'O valor do crédito inserido é menor que R$ 52,90, colque outro valor.',
                      'error'
                    );
                } else {
                    $.post('{% url "dashboard:create-payment" %}', {amount: amount}, function (response) {
                       window.location.href = response.url;
                    });
                }
            });
        });
    </script>
{% endblock %}